
springdoc.swagger-ui.path=/api-docs.html
springdoc.api-docs.path=/api-docs
springdoc.packagesToScan=pedidos_rabbit_api.controller

rabbitmq.exchange.name=pedidos.v1.pedido-criado

spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672