spring.application.name=processador-pedidos

rabbitmq.exchange.name=pedidos.v1.pedido-criado
rabbitmq.queue.name=pedidos.v1.pedido-criado.gerar-processamento

spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672


spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos-api
spring.datasource.driver-classe-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

